author = 'Aarav Kashyap'
def crazy_lib():
    global author
    print("Welcome to Aarav's Craaaazy Libs Story!")
    print("Hope you have a fun time!")
    name1 = input('Please give me a name or relative with capitalization.')
    noun1 = input('Please give me a noun.')
    noun2 = input('Please give me a noun.')
    adjective1 = input('Please give me a adjective.')
    adjective2 = input('Please give me a adjective.')
    verb1 = input('Please give me a verb in present tense(ing).')
    verb2 = input('Please give me a verb in present tense(ing).')
    adjective3 = input('Please give me a adjective.')
    noun3 = input('Please give me a noun.')
    verb3 = input('Please give me a verb.')
    adjective4 = input('Please give me a adjective.')
    name2 = input('Please give me a name or relative with capitalization.')
    name3 = input('Please give me a name or relative with capitalization.')
    noun4 = input('Please give me a body part.')
    noun5 = input('Please give me a noun.')
    noun6 = input('Please give me a location.')
    noun7 = input('Please give me a singular noun.')
    noun8 = input('Please give me a singular noun.')
    noun9 = input('Please give me a singular noun.')
    name4 = input('Please give me a name or relative with capitalization.')
    print("Dear,",name1,"\nYou have been invited to the",adjective1,"wedding of",adjective2,name2,"and",adjective3,name3,".")
    print("During the wedding you will have the honor of seeing",name2,"and",name3,verb1,"each other.")
    print("After they",verb1,"each other, they will all feast on",noun1,"at the",noun2,"restaurant.")
    print("Then at the",noun3,"ceremony, they will",verb2,"the",noun3,"on each others",noun4,".")
    print("After the",noun3,"ceremony",name2,"and",name3,"will",verb3,"then cut the",noun5,".")
    print("Once the wedding is finished all guests will be directed to the",noun6,".")
    print("At the",noun6,"each guest will be given a",noun7,".")
    print("Then the guests will be excused into their",noun8,"where they will safely return to their",noun9,".")
    print("I hope that you will come to our",adjective4,"wedding")
    print("Sincerely,")
    print("     ",name4)

crazy_lib()