import time,re
    
author='hermes tsai from c5'

def hcrazylimbs():
    def breakk():
        time.sleep(0.5)
    print('____________________')
    print(' ')
    print('Hello there, welcome to my MAD LIBS WOOHOO YEAHHHHHH')
    print('____________________')
    print(' \n \n')
    breakk()
    namef1=input("What's one of your friend's name?\n")
    breakk()
    verb1=input("Give me an action of moving forward in past tense(e.g. walked or ran)!\n")
    breakk()
    noun1=input("Give me flavor of ice cream!\n")
    breakk()
    noun2=input("Give me a number!\n")
    breakk()
    namef2=input("What's another one of your friend's name?\n")
    breakk()
    noun3=input("Give me a color!\n")
    breakk()
    verb2=input("Give me an action of violence(can't be killed) in past tense!\n")
    breakk()
    bpart=input("Give me the name of a body part!")
    breakk()
    namef3=input("Give me a random name.\n")
    breakk()
    noun4=input("Give me a brand of an expensive purse bag.\n")
    breakk()
    verb3=input("Give me an action of moving up in past tense.\n")
    breakk()
    p=input("Give me a phrase of apology.\n")
    breakk()
    print("One day,",namef1,"wanted to get some ice cream. Seeing a nearby ice cream truck, he",verb1,"to there and cut the line. He said, 'Hello there sir. Could I please have",noun2,"scoops of",noun1,"ice cream? While the man in the truck was putting the ice cream on the ice cream cone, a guy behind",namef1,"named",namef2,"said, 'Hey it's you",namef1,"! That shirt of yours with",noun3,"stripes is pretty cool!",namef1,", thinking",namef2,"was sarcastic, ",verb2,"",namef2,"in the",bpart,"! Suddenly,",namef3,"came out of nowhere with a",noun4,"bag and",verb3,". Hey you who just did that to",namef2,"! Apologize! Right now!",namef1,"said, ok.",p,".")
    breakk()
    print("\nThis madlimbs was codes by",author,".")
