author = 'Junlan Wang'
def crazy_lib():
    global author
    person = input('Enter a person: ')
    person2 = input('Enter a person: ')
    verb1 = input('Enter a verb: ')
    verb2 = input('Enter a verb: ')
    adj1 = input('Enter a adjective: ')
    adj2 = input('Enter a adjective: ')
    adj3 = input('Enter a adjective: ')
    location = input('Enter a location: ')
    _object = input('Enter a object: ')
    _object2 = input('Enter a object: ')
    noun = input('Enter a noun: ')
    print('\n\n',person, 'was invited to a play date with', person2 + '.')
    print('When', person, 'arrived at', person2, '\'s house,', person2, 'was no where to be found.')
    print(person, 'looked around a little more and found a', adj1, _object, 'and when', person, 'picked', _object, 'up, the object started to', verb1 + '.')
    print(person2, 'then finally emerged from behind', person, 'and scared', person + '.')
    print(person2, 'asked what', person, 'wanted to do.')
    print(person, 'told', person2, 'he wanted to go to the', location + '.')
    print(person2, 'and', person, 'walked to the', location, 'there they found a', adj2, _object2, 'and a', noun+ '.')
    print('The', adj2, _object2, 'started to', verb2 + '.')
    print(person, 'also commented the', location, 'was', adj3 + '.')
    print('After they were done playing at the park,', person, 'and', person2, 'both went back to their houses.')